# Generated by Django 5.0.2 on 2024-02-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('distance_to_desk', models.FloatField()),
                ('closest_elevator_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevators',
            fields=[
                ('elevator_num', models.IntegerField(primary_key=True, serialize=False)),
                ('dist_to_door', models.FloatField()),
            ],
        ),
    ]
