# Generated by Django 5.0.2 on 2024-02-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='elevators',
            options={'managed': False},
        ),
    ]
