# Generated by Django 5.0.2 on 2024-02-23 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0002_alter_department_options_alter_elevators_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='elevators',
            table='elevators',
        ),
    ]
