# Generated by Django 5.0.2 on 2024-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend', '0003_alter_department_table_alter_elevators_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('doornum', models.IntegerField(db_column='DoorNum', primary_key=True, serialize=False)),
                ('closestparkinglot', models.IntegerField(db_column='ClosestParkingLot')),
            ],
            options={
                'db_table': 'door',
                'managed': False,
            },
        ),
    ]
